<form class="form contact-inchoo"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="* Required Fields"
>
    <fieldset class="fieldset">
        <div class="field required">
            <label class="label" for="field1"><span><?php echo __('Your Name:'); ?></span></label>
            <div class="control">
                <input name="name" id="field1" title="<?php echo __('Name'); ?>" value="" class="input-text required" type="text" />
            </div>
        </div>
        <div class="field required">
            <label for="email_address" class="label"><span><?php echo __('Your Email:'); ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" value="" title="<?php echo __('Email'); ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field required">
            <label for="phone" class="label"><span><?php echo __('Your Phone:'); ?></span></label>
            <div class="control">
                <input type="email" name="email" id="phone" value="" title="<?php echo __('Phone'); ?>" class="input-text" data-validate="{required:true, 'validate-number':true}">
            </div>
        </div>
        <div class="field">
            <label class="label" for="field3"><span><?php echo __('Question:'); ?></span></label>
            <div class="control">
                <textarea rows="10" cols="45" name="question" id="field3" title="<?php echo __('Question'); ?>" value=""></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>